export const icons = {
  live: { ios: 'video.fill', android: 'videocam' },
  grid: { ios: 'square.grid.2x2.fill', android: 'grid_view' },
  grid1: { ios: 'rectangle.grid.1x2.fill', android: 'view_agenda' },
  grid3: { ios: 'square.grid.3x3.fill', android: 'apps' },
  playback: { ios: 'play.rectangle.on.rectangle.fill', android: 'video_library' },
  events: { ios: 'bell.fill', android: 'notifications' },
  manage: { ios: 'server.rack', android: 'dns' },
  settings: { ios: 'gearshape.fill', android: 'settings' },
  play: { ios: 'play.fill', android: 'play_arrow' },
  pause: { ios: 'pause.fill', android: 'pause' },
  speaker: { ios: 'speaker.wave.2.fill', android: 'volume_up' },
  speakerOff: { ios: 'speaker.slash.fill', android: 'volume_off' },
  mic: { ios: 'mic.fill', android: 'mic' },
  snapshot: { ios: 'camera.fill', android: 'photo_camera' },
  photo: { ios: 'photo', android: 'image' },
  share: { ios: 'square.and.arrow.up', android: 'share' },
  download: { ios: 'arrow.down.to.line', android: 'download' },
  expand: { ios: 'arrow.up.left.and.arrow.down.right', android: 'open_in_full' },
  pip: { ios: 'pip.enter', android: 'picture_in_picture_alt' },
  ptz: { ios: 'dpad.fill', android: 'open_with' },
  qr: { ios: 'qrcode.viewfinder', android: 'qr_code_scanner' },
  link: { ios: 'link', android: 'link' },
  server: { ios: 'server.rack', android: 'dns' },
  globe: { ios: 'globe', android: 'language' },
  lock: { ios: 'lock.fill', android: 'lock' },
  faceid: { ios: 'faceid', android: 'fingerprint' },
  bell: { ios: 'bell.badge', android: 'notifications_active' },
  moon: { ios: 'circle.lefthalf.filled', android: 'contrast' },
  info: { ios: 'info.circle', android: 'info' },
  doc: { ios: 'doc.text', android: 'description' },
  heart: { ios: 'heart', android: 'favorite' },
  code: { ios: 'chevron.left.forwardslash.chevron.right', android: 'code' },
  shield: { ios: 'hand.raised.fill', android: 'privacy_tip' },
  chevronRight: { ios: 'chevron.right', android: 'chevron_right' },
  chevronLeft: { ios: 'chevron.left', android: 'chevron_left' },
  chevronDown: { ios: 'chevron.down', android: 'keyboard_arrow_down' },
  chevronUp: { ios: 'chevron.up', android: 'keyboard_arrow_up' },
  close: { ios: 'xmark', android: 'close' },
  plus: { ios: 'plus', android: 'add' },
  minus: { ios: 'minus', android: 'remove' },
  trash: { ios: 'trash', android: 'delete' },
  pencil: { ios: 'pencil', android: 'edit' },
  check: { ios: 'checkmark', android: 'check' },
  checkCircle: { ios: 'checkmark.circle.fill', android: 'check_circle' },
  warning: { ios: 'exclamationmark.triangle.fill', android: 'warning' },
  wifi: { ios: 'wifi', android: 'wifi' },
  offline: { ios: 'video.slash.fill', android: 'videocam_off' },
  record: { ios: 'record.circle', android: 'radio_button_checked' },
  motion: { ios: 'figure.walk.motion', android: 'directions_run' },
  calendar: { ios: 'calendar', android: 'calendar_month' },
  back10: { ios: 'gobackward.10', android: 'replay_10' },
  fwd10: { ios: 'goforward.10', android: 'forward_10' },
  clip: { ios: 'scissors', android: 'content_cut' },
  person: { ios: 'person.crop.circle', android: 'account_circle' },
  people: { ios: 'person.2.fill', android: 'group' },
  storage: { ios: 'externaldrive.fill', android: 'storage' },
  cloud: { ios: 'icloud.fill', android: 'cloud' },
  cpu: { ios: 'cpu', android: 'memory' },
  logs: { ios: 'list.bullet.rectangle', android: 'receipt_long' },
  radar: { ios: 'antenna.radiowaves.left.and.right', android: 'sensors' },
  search: { ios: 'magnifyingglass', android: 'search' },
  refresh: { ios: 'arrow.clockwise', android: 'refresh' },
  more: { ios: 'ellipsis', android: 'more_horiz' },
  copy: { ios: 'doc.on.doc', android: 'content_copy' },
  external: { ios: 'arrow.up.right.square', android: 'open_in_new' },
  logout: { ios: 'rectangle.portrait.and.arrow.right', android: 'logout' },
  key: { ios: 'key.fill', android: 'key' },
  reorder: { ios: 'line.3.horizontal', android: 'drag_handle' },
  gateway: { ios: 'point.3.connected.trianglepath.dotted', android: 'hub' },
  eye: { ios: 'eye', android: 'visibility' },
  eyeOff: { ios: 'eye.slash', android: 'visibility_off' },
  home: { ios: 'house.fill', android: 'home' },
  bolt: { ios: 'bolt.fill', android: 'bolt' },
  star: { ios: 'star.fill', android: 'star' },
  power: { ios: 'power', android: 'power_settings_new' },
  disk: { ios: 'internaldrive.fill', android: 'hard_drive' },
  filter: { ios: 'line.3.horizontal.decrease', android: 'filter_list' },
  rotate: { ios: 'rotate.right', android: 'screen_rotation' },
  tag: { ios: 'tag', android: 'label' },
  zoomIn: { ios: 'plus.magnifyingglass', android: 'zoom_in' },
  zoomOut: { ios: 'minus.magnifyingglass', android: 'zoom_out' },
  speed: { ios: 'gauge.with.needle', android: 'speed' },
  folder: { ios: 'folder.fill', android: 'folder' },
  sliders: { ios: 'slider.horizontal.3', android: 'tune' },
  camera: { ios: 'video', android: 'videocam' },
  airplay: { ios: 'airplayvideo', android: 'cast' },
} as const;

export type IconName = keyof typeof icons;

export const filledOnAndroid: Partial<Record<IconName, boolean>> = {
  live: true,
  grid: true,
  grid1: true,
  grid3: true,
  playback: true,
  events: true,
  settings: true,
  play: true,
  pause: true,
  speaker: true,
  speakerOff: true,
  mic: true,
  snapshot: true,
  lock: true,
  bell: true,
  checkCircle: true,
  warning: true,
  offline: true,
  people: true,
  storage: true,
  cloud: true,
  key: true,
  home: true,
  bolt: true,
  star: true,
  disk: true,
  folder: true,
  shield: true,
};
